baseurl = "https://blog.zacharyjia.me"
languageCode = "zh-cn"
theme = "stack"
paginate = 10
title = "Zachary's Blog"
disqusShortname = "zachary-blog"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "cn"                   # Theme i18n support


[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
        
    [params.sidebar]
        emoji = "🍥"
        avatar = "img/avatar.png"
        subtitle = "贾泽群的个人博客"
        
    [params.article]
        math = false
        [params.article.license]
            enabled = true 
            default = "Licensed under CC BY-NC-ND 4.0"
            
    [params.comments]
        enabled = false
        provider = "disqus"         # Available: disqus, utterances    
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"
            
    [params.widgets]
        enabled = ['search', 'archives', 'tag-cloud']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"       
        [params.widgets.tagCloud]
            limit = 10
            
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "主页"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "关于"
        url = "about"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "archives"
        weight = -70
        pre = "archives"
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "search"
        weight = -60
        pre = "search"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false
